### ISSUE TITLE
Client side of Next apps is not able to access proshop-api

### ISSUE THREAD

**Issue by nareshbhatia** [nareshbhatia/proshop-nx#1]
In docker-compose.yaml, we specify the `NX_API_URL` environment variable as follows:

```
  proshop-catalog:
    image: nareshbhatia/proshop-nx-catalog:1.0.0
    ports:
      - '3001:3001'
    depends_on:
      - proshop-api
    environment:
      - NX_API_URL=http://proshop-api:8080

  proshop-api:
    image: nareshbhatia/proshop-nx-api:1.0.0
    ports:
      - '8080:8080'
```

This works for the server side, but client side is not able to access `http://proshop-api:8080`. The `proshop-api` domain is not known to the client.

We were able to work around this issue when deploying individual docker containers by specifying actual IP address of the machine. For example:

```sh
docker run -d --name proshop-nx-catalog -p 3001:3001 -e NX_API_URL=http://192.168.86.247:8080 nareshbhatia/proshop-nx-catalog:1.0.0
```

But this is a pure hack!!
